config/routes.rb
Ratebeer::Application.routes.draw do

  resources :styles

  resources :memberships

  resources :beerclubs

  resources :users

  root 'breweries#index'

  resources :beers

  resources :breweries

  resources :sessions, only: [:new, :create]
  resources :ratings, :only => [:index, :new, :create, :destroy]

  get 'beerlist', to:'beers#list'
  get 'ngbeerlist', to:'beers#nglist'
  get 'brewerylist', to: 'breweries#list'

  get 'ratings', to: 'ratings#index'
  get 'ratings/new', to:'ratings#new'

  post 'ratings', to: 'ratings#create'

  get 'kaikki_bisset', to: 'beers#index'

  get 'signup', to: 'users#new'
  get 'signin', to: 'sessions#new'
  delete 'signout', to: 'sessions#destroy'

  resources :places, only:[:index, :show]
  post 'places', to:'places#search'

end

app/models/beerclub.rb
class Beerclub < ActiveRecord::Base
  has_many :memberships, :dependent => :destroy
  has_many :users, through: :memberships
end

app/controllers/beerclubs_controller.rb
class BeerclubsController < ApplicationController
  before_action :set_beerclub, only: [:show, :edit, :update, :destroy]
  before_action :ensure_that_signed_in, except: [:index, :show]
  before_action :ensure_that_user_is_admin, only: [:destroy]

  # GET /beerclubs
  # GET /beerclubs.json
  def index
    @beerclubs = Beerclub.all
  end

  # GET /beerclubs/1
  # GET /beerclubs/1.json
  def show
    @membership = Membership.new
    @membership.user = current_user
    @membership.beerclub = @beerclub
  end

  # GET /beerclubs/new
  def new
    @beerclub = Beerclub.new
  end

  # GET /beerclubs/1/edit
  def edit
  end

  # POST /beerclubs
  # POST /beerclubs.json
  def create
    @beerclub = Beerclub.new(beerclub_params)

    respond_to do |format|
      if @beerclub.save
        format.html { redirect_to @beerclub, notice: 'Beerclub was successfully created.' }
        format.json { render action: 'show', status: :created, location: @beerclub }
      else
        format.html { render action: 'new' }
        format.json { render json: @beerclub.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /beerclubs/1
  # PATCH/PUT /beerclubs/1.json
  def update
    respond_to do |format|
      if @beerclub.update(beerclub_params)
        format.html { redirect_to @beerclub, notice: 'Beerclub was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @beerclub.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /beerclubs/1
  # DELETE /beerclubs/1.json
  def destroy
    @beerclub.destroy
    respond_to do |format|
      format.html { redirect_to beerclubs_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_beerclub
      @beerclub = Beerclub.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def beerclub_params
      params.require(:beerclub).permit(:name, :founded, :city)
    end
end

app/helpers/beerclubs_helper.rb
module BeerclubsHelper
end

app/views/beerclubs/_form.html.erb
<%= form_for(@beerclub) do |f| %>
  <% if @beerclub.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@beerclub.errors.count, "error") %> prohibited this beerclub from being saved:</h2>

      <ul>
      <% @beerclub.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :founded %><br>
    <%= f.number_field :founded %>
  </div>
  <div class="field">
    <%= f.label :city %><br>
    <%= f.text_field :city %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/beerclubs/edit.html.erb
<h1>Editing beerclub</h1>

<%= render 'form' %>

<%= link_to 'Show', @beerclub %> |
<%= link_to 'Back', beerclubs_path %>

app/views/beerclubs/index.html.erb
<h1>Listing beerclubs</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Founded</th>
      <th>City</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @beerclubs.each do |beerclub| %>
      <tr>
        <td><%= beerclub.name %></td>
        <td><%= beerclub.founded %></td>
        <td><%= beerclub.city %></td>
        <td><%= link_to 'Show', beerclub %></td>
        <td><%= link_to 'Edit', edit_beerclub_path(beerclub) %></td>
        <td><%= link_to 'Destroy', beerclub, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Beerclub', new_beerclub_path %>

app/views/beerclubs/new.html.erb
<h1>New beerclub</h1>

<%= render 'form' %>

<%= link_to 'Back', beerclubs_path %>

app/views/beerclubs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @beerclub.name %>
</p>

<p>
  <strong>Founded:</strong>
  <%= @beerclub.founded %>
</p>

<p>
  <strong>City:</strong>
  <%= @beerclub.city %>
</p>

<% if @beerclub.users.empty? %>
	<p>No members</p>
<% else %>
	<p>Beerclub has <%= pluralize(@beerclub.users.count, "member") %></p>
	
	<ul>
  	<% @beerclub.users.each do |user| %>
    	<li> <%= link_to user.username, user %> </li>
  	<% end %>
	</ul>
	
<% end %>

<% if current_user and not current_user.beerclubs.include?(@beerclub) %>
<%= form_for(@membership) do |f| %>
    <%= f.hidden_field :beerclub_id %>
    <%= f.submit value:"Join this beerclub" %>
 <% end %>
<% end %>

<%= link_to 'Edit', edit_beerclub_path(@beerclub) if current_user %>