config/routes.rb
Ratebeer::Application.routes.draw do

  resources :styles

  resources :memberships

  resources :beerclubs

  resources :users

  root 'breweries#index'

  resources :beers

  resources :breweries

  resources :sessions, only: [:new, :create]
  resources :ratings, :only => [:index, :new, :create, :destroy]

  get 'beerlist', to:'beers#list'
  get 'ngbeerlist', to:'beers#nglist'
  get 'brewerylist', to: 'breweries#list'

  get 'ratings', to: 'ratings#index'
  get 'ratings/new', to:'ratings#new'

  post 'ratings', to: 'ratings#create'

  get 'kaikki_bisset', to: 'beers#index'

  get 'signup', to: 'users#new'
  get 'signin', to: 'sessions#new'
  delete 'signout', to: 'sessions#destroy'

  resources :places, only:[:index, :show]
  post 'places', to:'places#search'

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Ratebeer</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<div id="page">

<div class="navibar">
<%= link_to 'Breweries', breweries_path %>
<%= link_to 'Places', places_path %>
<%= link_to 'Beers', beers_path %>
<%= link_to 'Styles', styles_path %>
<%= link_to 'BeerClubs', beerclubs_path %>
<%= link_to 'Ratings', ratings_path %>
<%= link_to 'Users', users_path %> |

<% if not current_user.nil? %>
  <%= link_to current_user.username, current_user %> 
  <%= link_to "rate a beer", new_rating_path %>
  <%= link_to "join a club", new_membership_path %>
  <%= link_to "signout", signout_path, method: :delete %>
<% else %>
  <%= link_to "signin", new_session_path %>
  <%= link_to "signup", signup_path %>
<% end %>


</div>



<%= yield %>

</div>
</body>
</html>